import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "../components/providers";
import Navbar from "@/components/Navbar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{
          background: `
          radial-gradient(ellipse at 15% 25%, rgba(200, 195, 215, 0.95) 0%, transparent 50%),
          radial-gradient(ellipse at 85% 75%, rgba(175, 185, 205, 0.9) 0%, transparent 50%),
          radial-gradient(ellipse at 60% 10%, rgba(225, 218, 230, 0.8) 0%, transparent 45%),
          radial-gradient(ellipse at 30% 80%, rgba(190, 200, 220, 0.7) 0%, transparent 40%),
          radial-gradient(ellipse at 90% 20%, rgba(210, 205, 225, 0.75) 0%, transparent 40%),
          #bfc5d3
        `,
        }}
      >
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
